import os
import uuid
import logging
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, UploadFile, File, Form, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel


from backend.config import settings
from backend.parsers.pdf_parser import parse_pdf
from backend.parsers.docx_parser import parse_docx
from backend.services.chunker import chunk_legal_document, ClauseChunk
from backend.services.gemini_service import (
    analyze_document_with_gemini,
    compare_documents_with_gemini
)
from backend.services.rag_engine import (
    DocumentVectorStore,
    SESSION_INDEX_STORE,
    answer_document_question
)
from backend.samples.generate_samples import build_seed_samples, SAMPLE_LEASE_TEXT, SAMPLE_NDA_TEXT

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("lexclear-backend")

# Ensure sample documents exist at startup
build_seed_samples()

app = FastAPI(
    title="LexClear API",
    description="AI-Powered Legal Document Assistant API",
    version="1.0.0"
)

# Enable CORS for Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory document session cache
# Stores parsed doc text & metadata per session
DOCUMENT_SESSION_CACHE: Dict[str, Dict[str, Any]] = {}

class ChatRequest(BaseModel):
    doc_id: str
    query: str
    api_key: Optional[str] = None

class CompareRequest(BaseModel):
    doc_a_id: str
    doc_b_id: str
    api_key: Optional[str] = None

@app.get("/api/health")
def health_check():
    return {
        "status": "online",
        "service": "LexClear AI Legal Document Assistant",
        "disclaimer": "Informational tool only. Not legal advice."
    }


@app.get("/api/samples")
def list_samples():
    """Returns available seed sample documents for 1-click evaluation."""
    return [
        {
            "key": "residential_lease",
            "title": "🏡 Residential Lease Agreement",
            "description": "Standard 12-month apartment lease with auto-renewal, late fee penalties, and right of entry clauses.",
            "file_type": "PDF"
        },
        {
            "key": "employment_nda",
            "title": "💼 Employment NDA & IP Assignment",
            "description": "Corporate agreement with broad IP ownership rights, 24-month non-compete, and mandatory Delaware arbitration.",
            "file_type": "PDF"
        }
    ]

def process_document_text(doc_id: str, title: str, text: str, api_key: Optional[str] = None) -> Dict[str, Any]:
    """Helper method to chunk text, run Gemini analysis, and build RAG vector index."""
    chunks = chunk_legal_document(text)
    
    # Store in RAG session index
    vstore = DocumentVectorStore(doc_id, chunks)
    # Background index build or immediate
    vstore.build_index(api_key=api_key)
    SESSION_INDEX_STORE[doc_id] = vstore
    
    # Gemini AI Analysis
    analysis = analyze_document_with_gemini(text, api_key=api_key)
    
    doc_result = {
        "doc_id": doc_id,
        "title": title,
        "word_count": len(text.split()),
        "clause_count": len(chunks),
        "raw_text": text,
        "chunks": [c.model_dump() for c in chunks],
        "analysis": analysis,
        "disclaimer": "This is general informational analysis generated by AI, not legal advice."
    }
    
    DOCUMENT_SESSION_CACHE[doc_id] = doc_result
    return doc_result

@app.post("/api/upload")
async def upload_document(
    file: UploadFile = File(...),
    x_gemini_api_key: Optional[str] = Header(None)
):
    """Uploads and analyzes a legal document (PDF or DOCX)."""
    filename = file.filename or "uploaded_document"
    contents = await file.read()
    
    if filename.lower().endswith(".pdf"):
        text = parse_pdf(contents)
    elif filename.lower().endswith(".docx"):
        text = parse_docx(contents)
    elif filename.lower().endswith(".txt"):
        text = contents.decode("utf-8", errors="ignore")
    else:
        # Try decoding as text
        text = contents.decode("utf-8", errors="ignore")
        
    if not text.strip():
        raise HTTPException(status_code=400, detail="Could not extract readable text from uploaded file.")
        
    doc_id = str(uuid.uuid4())
    try:
        result = process_document_text(doc_id, filename, text, api_key=x_gemini_api_key)
        return result
    except Exception as e:
        logger.error(f"Error processing document upload: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/load-sample/{sample_key}")
def load_sample_document(
    sample_key: str,
    x_gemini_api_key: Optional[str] = Header(None)
):
    """Loads and analyzes a pre-seeded sample document."""
    if sample_key == "residential_lease":
        title = "Residential Lease Agreement.pdf"
        text = SAMPLE_LEASE_TEXT
    elif sample_key == "employment_nda":
        title = "Employment NDA & IP Assignment.pdf"
        text = SAMPLE_NDA_TEXT
    else:
        raise HTTPException(status_code=404, detail="Sample document key not found.")
        
    doc_id = f"sample_{sample_key}"
    try:
        result = process_document_text(doc_id, title, text, api_key=x_gemini_api_key)
        return result
    except Exception as e:
        logger.error(f"Error processing sample document {sample_key}: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/chat")
def chat_with_document(
    req: ChatRequest,
    x_gemini_api_key: Optional[str] = Header(None)
):
    """Chat endpoint for Q&A on indexed document with citations and guardrails."""
    effective_key = req.api_key or x_gemini_api_key
    res = answer_document_question(
        doc_id=req.doc_id,
        query=req.query,
        api_key=effective_key
    )
    return res

@app.post("/api/compare")
def compare_documents(
    req: CompareRequest,
    x_gemini_api_key: Optional[str] = Header(None)
):
    """Compares two uploaded/session documents side-by-side."""
    doc_a = DOCUMENT_SESSION_CACHE.get(req.doc_a_id)
    doc_b = DOCUMENT_SESSION_CACHE.get(req.doc_b_id)
    
    if not doc_a or not doc_b:
        raise HTTPException(status_code=400, detail="One or both document sessions not found.")
        
    try:
        comparison = compare_documents_with_gemini(
            doc_a_text=doc_a["raw_text"],
            doc_b_text=doc_b["raw_text"],
            doc_a_name=doc_a["title"],
            doc_b_name=doc_b["title"],
            api_key=req.api_key or x_gemini_api_key
        )
        return {
            "doc_a": {"id": req.doc_a_id, "title": doc_a["title"]},
            "doc_b": {"id": req.doc_b_id, "title": doc_b["title"]},
            "comparison": comparison
        }
    except Exception as e:
        logger.error(f"Error comparing documents: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# Mount static frontend build if present
static_dir = os.path.join(os.path.dirname(__file__), "..", "frontend", "out")
if os.path.exists(static_dir):
    app.mount("/", StaticFiles(directory=static_dir, html=True), name="static")

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("backend.main:app", host="0.0.0.0", port=port, reload=True)

